export const siteConfig = {
  title: "AgroCylo 🌾",
  description:
    "Peer-to-peer agro marketplace secured by Stellar escrow. Farmers sell directly to buyers — no middlemen, no chargebacks.",

  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },

  ogTitle: "AgroCylo — Fair Trade. On-chain. For Every Farmer.",
  ogDescription:
    "Our platform connects farmers directly with buyers — Stellar escrow guarantees fair settlement, lower fees, and faster payouts.",

  // Auto-generated by app/opengraph-image.tsx — no static file needed
  ogImage: "/opengraph-image",

  url: "https://agrocylo.vercel.app",

  tCard: "summary_large_image" as const,
  tTitle: "AgroCylo — Fair Trade. On-chain. For Every Farmer.",
  tDescription:
    "Our platform connects farmers directly with buyers — Stellar escrow guarantees fair settlement, lower fees, and faster payouts.",
};
